repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        exclude: packaging/.*
        args:
          - --allow-multiple-documents
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
  
  # - repo: git@github.com:psf/black.git
  #   rev: stable
  #   hooks:
  #   - id: black
  #     language_version: python3.10

  - repo: git@github.com:PyCQA/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [--config=setup.cfg]
  
  # - repo: https://github.com/timothycrosley/isort
  - repo: git@github.com:PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=setup.cfg]
